classes:
  Tier 1:
    Economic:
      - Prospector
      - Handyman
      - Demolisher
    Combat:
      - Archer
      - Warrior
      - Axeman
  Tier 2:
    Economic:
      - Mayor
      - Merchant
      - Engineer
    Combat:
      - Mage
      - Paladin
      - Hunter
  Tier 3:
    Economic:
      - Rider
      - Politician
      - CEO
    Combat:
      - Survivalist
      - Spartan
      - Sorceror
