classes:
  Tier 1:
    Economic:
      Prospector:
        bind: []
        unbind: []
      Handyman:
        bind: []
        unbind: []
      Demolisher:
        bind: []
        unbind: []
    Combat:
      Archer:
        bind: []
        unbind: []
      Warrior:
        bind: []
        unbind: []
      Axeman:
        bind: []
        unbind: []
  Tier 2:
    Economic:
      Mayor:
        bind: []
        unbind: []
      Merchant:
        bind: []
        unbind: []
      Engineer:
        bind: []
        unbind: []
    Combat:
      Mage:
        bind:
          - "/hero join"
      Paladin:
        bind: []
        unbind: []
      Hunter:
        bind: []
        unbind: []
  Tier 3:
    Economic:
      Rider:
        bind: []
        unbind: []
      Politician:
        bind: []
        unbind: []
      CEO:
        bind: []
        unbind: []
    Combat:
      Survivalist:
        bind: []
        unbind: []
      Spartan:
        bind: []
        unbind: []
      Sorceror:
        bind: []
        unbind: []
