name: ${project.name}
description: ${project.description}
author: AlbireoX
version: ${release.number}
website: ${project.url}

main: net.crimsoncraft.permclasses.PermClasses
depend: [Vault]

commands:
  pcl:
    description: PermClasses base command.
    usage: /pcl <action> [args]
    
permissions:
  pcl.admin:
    description: Grants access to all admin commands.
    default: op
    children:
      pcl.admin.set: true
      pcl.admin.rm: true
      pcl.admin.reload: true
      pcl.use.*: true
      
  pcl.admin.set:
    description: Allows setting of a player's class.
    
  pcl.admin.rm:
    description: Allows removal of a player's class.
    
  pcl.admin.reload:
    description: Allows reloading of the plugin.
    
  pcl.admin.sign.create:
    description: Allows the creation of signs.
    
  pcl.use.*:
    description: Allows the usage of all classes.